### ISSUE TITLE
arpc fails to build

### ISSUE THREAD

**Issue by sgielen** [NuxiNL/homebrew-cloudabi#2]
arpc `0.6` fails to build on my machine, build log:

[02.make.txt](https://github.com/NuxiNL/homebrew-cloudabi/files/1326832/02.make.txt)

It looks like it's because argdata is not in the include paths --- in fact, none of the dependencies are:

```
/usr/local/opt/llvm@4/bin/clang++  -Darpc_EXPORTS -I/tmp/arpc-20170923-85013-wxeq0j/arpc-0.6 -I/tmp/arpc-20170923-85013-wxeq0j/arpc-0.6/include -I/tmp/arpc-20170923-85013-wxeq0j/arpc-0.6/contrib/googletest-release-1.8.0/googletest/include -I/tmp/arpc-20170923-85013-wxeq0j/arpc-0.6/contrib/googletest-release-1.8.0/googletest  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -fPIC   -std=c++1z -o CMakeFiles/arpc.dir/src/argdata_parser.cc.o -c /tmp/arpc-20170923-85013-wxeq0j/arpc-0.6/src/argdata_parser.cc
/tmp/arpc-20170923-82952-1hnnzzf/arpc-0.6/src/argdata_parser.cc:8:10: fatal error: 'argdata.h' file not found
```

I would expect `-I/usr/local/Cellar/argdata/0.7/include` to be in the compiler flags.

**Comment by sgielen** [comment]
I've tried setting `argdata` to be a `:build` dependency but that didn't help.

Perhaps it's because arpc's `CMakeLists.txt` doesn't search for the argdata include dir? I'm not sure how it' supposed to find it when built through homebrew, but it doesn't automatically include `/usr/local/include` which is where `argdata.h` and `argdata.hpp` are.

**Comment by sgielen** [comment]
To confirm, the following change does fix the build, in all its ugliness:

```patch
-    system "cmake", ".", "-DCMAKE_C_COMPILER=#{Formula["llvm@4"].opt_bin}/clang", "-DCMAKE_CXX_COMPILER=#{Formula["llvm@4"].opt_bin}/clang++", *std_cmake_args
+    system "cmake", ".", "-DCMAKE_C_COMPILER=#{Formula["llvm@4"].opt_bin}/clang", "-DCMAKE_CXX_COMPILER=#{Formula["llvm@4"].opt_bin}/clang++",
+      "-DCMAKE_CXX_FLAGS=\"-I#{Formula["argdata"].include}\"", *std_cmake_args
```

**Comment by sgielen** [comment]
The same is true for flower, by the way. :-) There, the following patch 'fixes' the build:

```patch
-    system "cmake", ".", "-DCMAKE_C_COMPILER=#{Formula["llvm@4"].opt_bin}/clang", "-DCMAKE_CXX_COMPILER=#{Formula["llvm@4"].opt_bin}/clang++", *std_cmake_args
+    system "cmake", ".", "-DCMAKE_C_COMPILER=#{Formula["llvm@4"].opt_bin}/clang", "-DCMAKE_CXX_COMPILER=#{Formula["llvm@4"].opt_bin}/clang++",
+      "-DCMAKE_CXX_FLAGS=-I#{Formula["argdata"].include} -I#{Formula["arpc"].include} -I#{Formula["jsoncpp"].include}", *std_cmake_args
```

Of course, this is not the right fix, but it confirms the problem.

**Comment by EdSchouten** [comment]
The annoying thing is that this is impossible for me to reproduce. Grepping through the Homebrew formulae, I'm also not able to figure out whether this way *is* the suggested way to do this. Maybe we should simply commit the changes you propose?

Sjors, could you turn the changes above into a pull request? Thanks!

**Comment by EdSchouten** [comment]
Oh, wait. You already have write access to this repository. Feel free to just commit those changes!

**Comment by EdSchouten** [comment]
Fixed! As suggested by Simon on IRC, this is due to https://github.com/Homebrew/brew/issues/556.

After running `sudo rm -Rf /Library/Developer/CommandLineTools`, I was able to reproduce this.
